### PR TITLE
Fixes for tuple syntax change and deprecations on 0.4

### PR DESCRIPTION
**Pull request by timholy**
This is on the road to a renewed effort to get travis testing for BinDeps working.

### CODE REVIEW

**Comment by timholy** [comment]
Oh, and whenever this gets merged, a new version will need to be tagged ASAP.

**Comment by timholy** [comment]
If I tag, then the tag won't be pushed to this repository. Could you do it, @StefanKarpinski?

**Comment by StefanKarpinski** [comment]
I just gave you the ability to push (and thus tag versions) instead :-)

**Comment by timholy** [comment]
Didn't work, but went ahead anyway. See https://github.com/JuliaLang/METADATA.jl/pull/2732

**Comment by timholy** [comment]
Ah, I just needed to check my email :-).

**Pull request merged**
